<a href="https://colab.research.google.com/github/denzilsaldanha/neural-nets-course/blob/master/part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#!/usr/bin/env python3
"""
part1.py

UNSW COMP9444 Neural Networks and Deep Learning

ONLY COMPLETE METHODS AND CLASSES MARKED "TODO".

DO NOT MODIFY IMPORTS. DO NOT ADD EXTRA FUNCTIONS.
DO NOT MODIFY EXISTING FUNCTION SIGNATURES.
DO NOT IMPORT ADDITIONAL LIBRARIES.
DOING SO MAY CAUSE YOUR CODE TO FAIL AUTOMATED TESTING.
"""
import torch

# Simple addition operation

def simple_addition(x, y):
    """
    TODO: Implement a simple addition function that accepts two tensors and returns the result.
    """
    ans = torch.add(x,y)
    return ans

# Resize tensors
# Use view() to implement the following functions ( flatten() and reshape() are not allowed )

def simple_reshape(x, shape):
    """
    TODO: Implement a function that reshapes the given tensor as the given shape and returns the result.
    """
    ans = x.view(shape)
    return ans


def simple_flat(x):
    """
    TODO: Implement a function that flattens the given tensor and returns the result.
    """
    ans = x.view(list(x.size())[0]*list(x.size())[0])
    return ans

# Transpose and Permutation

def simple_transpose(x):
    """
    TODO: Implement a function that swaps the first dimension and
        the second dimension of the given matrix x and returns the result.
    """
    ans = x.t()
    return ans

def simple_permute(x, order):
    """
    TODO: Implement a function that permute the dimensions of the given tensor
        x according to the given order and returns the result.
    """
    ans = x.permute(list(order))
    return ans

# Matrix multiplication (with broadcasting).

def simple_dot_product(x, y):
    """
    TODO: Implement a function that computes the dot product of
        two rank 1 tensors and returns the result.
    """
    ans = torch.dot(x,y)
    return ans


def simple_matrix_mul(x, y):
    """
    TODO: Implement a function that performs a matrix multiplication
        of two given rank 2 tensors and returns the result.
    """
    ans = x@y
    return ans

def broadcastable_matrix_mul(x, y):
    """
    TODO: Implement a function that computes the matrix product of two tensors and returns the result.
        The function needs to be broadcastable.
    """
    ans = torch.matmul(x,y)
    return ans

# Concatenate and stack.
def simple_concatenate(tensors):
    """
    TODO: Implement a function that concatenates the given sequence of tensors
        in the first dimension and returns the result
    """
    ans = torch.cat(tensors,0)
    return ans


def simple_stack(tensors, dim):
    """
    TODO: Implement a function that concatenates the given sequence of tensors
        along a new dimension(dim) and returns the result.
    """
    ans = torch.stack(tensors, dim=dim)
    return ans 



In [0]:
simple_addition(torch.tensor([2,3,4]),torch.tensor([3,4,5]))

tensor([5, 7, 9])

In [0]:
simple_flat(torch.Tensor([[1,2,3],[4,5,6],[7,8,9]]))

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [0]:
simple_reshape(torch.Tensor([[1,2,3,4,5,6,7,8,9]]), (3,3))

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [0]:
simple_transpose(torch.tensor([[1,2,3],[4,5,6],[7,8,9]]))

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [0]:
 x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [0]:
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [0]:
simple_permute(torch.tensor([[1,2],[3,4],[5,6],[6,7]]), [-2,1])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [6, 7]])

In [0]:
simple_dot_product(torch.tensor([1,2]), torch.tensor([3,4]))

tensor(11)

In [0]:

simple_matrix_mul(torch.rand(2,3), torch.randn(3,3))

tensor([[ 0.1953, -1.3506, -1.7399],
        [ 0.3747, -0.9461, -1.2183]])

In [0]:
broadcastable_matrix_mul(torch.rand(64,3,10,10), torch.rand(12,1,1,10,10))

tensor([[[[[2.2124, 2.6767, 1.9970,  ..., 2.3359, 1.0248, 1.0427],
           [3.4322, 3.8804, 2.7010,  ..., 3.4515, 2.0082, 1.5677],
           [2.8973, 3.7323, 2.3612,  ..., 3.5986, 1.8649, 1.7519],
           ...,
           [2.9634, 3.7071, 2.2334,  ..., 3.3670, 1.8583, 1.5302],
           [3.1048, 4.0300, 2.8331,  ..., 3.4314, 2.1386, 1.5266],
           [2.7224, 3.2485, 2.3731,  ..., 2.5607, 1.3455, 1.3651]],

          [[3.0021, 4.0226, 2.8544,  ..., 2.9975, 1.8559, 1.3023],
           [3.3685, 4.1741, 2.8933,  ..., 3.3105, 2.0910, 1.4414],
           [2.0049, 2.6053, 1.5363,  ..., 3.0381, 1.6196, 1.4678],
           ...,
           [3.1530, 3.6367, 2.6028,  ..., 3.6268, 1.8153, 1.7630],
           [3.2251, 4.0456, 2.7504,  ..., 3.8685, 2.1537, 1.7359],
           [1.6016, 2.2675, 1.2008,  ..., 2.2012, 1.4843, 0.9844]],

          [[2.4857, 2.9541, 1.6050,  ..., 2.4213, 1.3065, 1.1355],
           [3.3172, 4.0280, 2.5369,  ..., 2.9511, 1.5298, 1.6017],
           [2.6709, 3.1533

In [0]:
tensor_list = [torch.rand(2,3,4), torch.rand(2,3,4), torch.rand(2,3,4)]
tensor_list

[tensor([[[0.5835, 0.3068, 0.9042, 0.0175],
          [0.3886, 0.7143, 0.9522, 0.3165],
          [0.1864, 0.1188, 0.4265, 0.8985]],
 
         [[0.4196, 0.6857, 0.8301, 0.5191],
          [0.4927, 0.8216, 0.1042, 0.9665],
          [0.8551, 0.8411, 0.4886, 0.9273]]]),
 tensor([[[0.4010, 0.7480, 0.9923, 0.0726],
          [0.8721, 0.3596, 0.8399, 0.4992],
          [0.6005, 0.9748, 0.6604, 0.9369]],
 
         [[0.7942, 0.4138, 0.0336, 0.3941],
          [0.7051, 0.5848, 0.8185, 0.6166],
          [0.3739, 0.0072, 0.7477, 0.5366]]]),
 tensor([[[0.6368, 0.4398, 0.3495, 0.4673],
          [0.1941, 0.0355, 0.2167, 0.3013],
          [0.4585, 0.4338, 0.7235, 0.6388]],
 
         [[0.9203, 0.6689, 0.5926, 0.0050],
          [0.9694, 0.8928, 0.7080, 0.6727],
          [0.5632, 0.9240, 0.5212, 0.0307]]])]

In [0]:
simple_stack(tensor_list, 3)

tensor([[[[0.5835, 0.4010, 0.6368],
          [0.3068, 0.7480, 0.4398],
          [0.9042, 0.9923, 0.3495],
          [0.0175, 0.0726, 0.4673]],

         [[0.3886, 0.8721, 0.1941],
          [0.7143, 0.3596, 0.0355],
          [0.9522, 0.8399, 0.2167],
          [0.3165, 0.4992, 0.3013]],

         [[0.1864, 0.6005, 0.4585],
          [0.1188, 0.9748, 0.4338],
          [0.4265, 0.6604, 0.7235],
          [0.8985, 0.9369, 0.6388]]],


        [[[0.4196, 0.7942, 0.9203],
          [0.6857, 0.4138, 0.6689],
          [0.8301, 0.0336, 0.5926],
          [0.5191, 0.3941, 0.0050]],

         [[0.4927, 0.7051, 0.9694],
          [0.8216, 0.5848, 0.8928],
          [0.1042, 0.8185, 0.7080],
          [0.9665, 0.6166, 0.6727]],

         [[0.8551, 0.3739, 0.5632],
          [0.8411, 0.0072, 0.9240],
          [0.4886, 0.7477, 0.5212],
          [0.9273, 0.5366, 0.0307]]]])

In [0]:
simple_concatenate(tensor_list)

tensor([[[0.5835, 0.3068, 0.9042, 0.0175],
         [0.3886, 0.7143, 0.9522, 0.3165],
         [0.1864, 0.1188, 0.4265, 0.8985]],

        [[0.4196, 0.6857, 0.8301, 0.5191],
         [0.4927, 0.8216, 0.1042, 0.9665],
         [0.8551, 0.8411, 0.4886, 0.9273]],

        [[0.4010, 0.7480, 0.9923, 0.0726],
         [0.8721, 0.3596, 0.8399, 0.4992],
         [0.6005, 0.9748, 0.6604, 0.9369]],

        [[0.7942, 0.4138, 0.0336, 0.3941],
         [0.7051, 0.5848, 0.8185, 0.6166],
         [0.3739, 0.0072, 0.7477, 0.5366]],

        [[0.6368, 0.4398, 0.3495, 0.4673],
         [0.1941, 0.0355, 0.2167, 0.3013],
         [0.4585, 0.4338, 0.7235, 0.6388]],

        [[0.9203, 0.6689, 0.5926, 0.0050],
         [0.9694, 0.8928, 0.7080, 0.6727],
         [0.5632, 0.9240, 0.5212, 0.0307]]])